# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad639c0aefa9440e3a25c6e9396a7303ee910f3f4243880437556f85baf5ff0149666145cebbb9720f22e97cf8732057ba9c393e39190bc0dffe211dd38838f3

test:
  secret_key_base: 833e2369d17b7da4ce082a9af3cc6d4c5f9c984ad2a9155ee963af9de383b66c53f6dd291cf16126e5794c60892eb42554c35c91d054d072acd3fbeb1563b463

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
